### ISSUE TITLE
Add Snapshot function for tags

### ISSUE THREAD

**Issue by apletnev** [rtdip/core#411]
**Is your feature request related to a problem? Please describe.**

I want to retrieve the latest snapshot of a specific tag. Unfortunately, all RTDIP functions have a time window, so I can't get the latest value because I don't have a time window.

**Describe the solution you'd like**

I want to use a new function and API like this

```
parameters = {
    "business_unit": "Business Unit",
    "region": "Region", 
    "asset": "Asset Name", 
    "data_security_level": "Security Level", 
    "data_type": "float", #options:["float", "double", "integer", "string"]
    "tag_names": ["tag_1", "tag_2"], #list of tags
    "include_bad_data": True, #options: [True, False]
}
x = snapshot.get(connection, parameters)
```

**Describe alternatives you've considered**

No alternatives

**Additional context**

None

**Comment by GBBBAS** [comment]
Hey @apletnev - we've now released updates to address getting snapshot latest values:

1. For Pipelines we have a new [latest destination component](https://www.rtdip.io/sdk/code-reference/pipelines/destinations/spark/pcdm_latest_to_delta/)
2. For SDK Queries we have the new [latest query](https://www.rtdip.io/sdk/code-reference/query/query_builder/#src.sdk.python.rtdip_sdk.queries.query_builder.QueryBuilder.latest)
3. For the API, we have the equivalent [latest API](https://github.com/rtdip/core/blob/develop/src/api/v1/latest.py)

Once the latest destination component is incorporated into your pipeline, you can then utilize the queries to access it.
