### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by MrDaggubati** [rtdip/core#538]
That's a nice chunk of work and appreciate for all the good work and moreover open sourcing it
Noticed there is a bit of of mixing with folder structure and also looks like crafted for shell requirements 
rather generic framework that can be worked our as a plugins/connectors/sources.

May be i am wrong in my understanding/grasping due to vastness of the sources/connectors that are crafted.
Below is what i see may need bit more re-factoring

 - utilities and models are bit spread into multiple sub directories
    core\src\sdk\python\rtdip_sdk\data_models\storage_objects\storage_objects_utils.py - can be under core\src\sdk\python\rtdip_sdk\pipelines\utilities\azure 

-  models
    some models are in utils some are in pipeline
    Weather & weather_ecmwf.py , obc_field_mappings are models but listed as part of pipeline.
    core\src\sdk\python\rtdip_sdk\pipelines\_pipeline_utils\obc_field_mappings.py
    core\src\sdk\python\rtdip_sdk\data_models\weather\weather_models.py

- core\src\sdk\python\rtdip_sdk\pipelines\_pipeline_utils\models.py is more of dependencies(libs.jar's)

**Comment by GBBBAS** [comment]
Many thanks for the feedback - we will work through these in a more general review of the structure of the repo.
