### ISSUE TITLE
Databricks SQL fetch command does not work

### ISSUE THREAD

**Issue by DuncanGan-Shell** [rtdip/core#55]
**Describe the bug**

DatabricksSQLCursor has no attribute fetchall() called from https://github.com/rtdip/core/blob/63788231630272a2f25c3caca7b5d21cd6d17278/src/sdk/python/rtdip_sdk/odbc/db_sql_connector.py#L93

**To Reproduce**

Create SQL end point connection to a cursor: 
```
from rtdip_sdk.odbc import db_sql_connector as d
connection =  d.DatabricksSQLConnection(server_hostname=server_hostname, http_path=http_path, access_token=access_token)
cursor = d.DatabricksSQLCursor(connection.cursor())
```

Execute Query on Cursor 
`cursor.execute(query)`

Confirm on Databricks SQL that query has executed on cluster

Retrieve results: 
`result = cursor.fetch_all()`

**Expected behavior**

Retrieve data from query in DataFrame

**Screenshots**

![image](https://user-images.githubusercontent.com/77772321/216178911-795b46ea-d393-4726-8379-43447bfef585.png)

**Additional Info**

I believe the error stems from the ABC Meta that it looking to pass the function fetch_all() rather than fetchall() 
https://github.com/rtdip/core/blob/63788231630272a2f25c3caca7b5d21cd6d17278/src/sdk/python/rtdip_sdk/odbc/cursor_interface.py#L26-L28

using the databricks lib directly the fetchall() command is the correct function.

**Comment by GBBBAS** [comment]
Thanks @DuncanGan-Shell - useful information and will pick this up now

**Comment by GBBBAS** [comment]
@DuncanGan-Shell the issue is related to the line of code 
`cursor = d.DatabricksSQLCursor(connection.cursor())`

if you change it to `cursor = connection.cursor()` it will work

We tested this on our side and the query was successful, so will close the ticket
