### ISSUE TITLE
Missing "Good" data from queries when Status Column != "Good" (e.g. is equal to "Substituted, Good")

### ISSUE THREAD

**Issue by matt-hull0** [rtdip/core#672]
**Describe the bug**

I **think** data can get missed and not used by the interpolate (and other) function(s) that manipulate raw data.

**A clear and concise description of what the bug is.**

The issue is because there are rows of raw data which are "Good data", but do not have the value `'Good'` in the Status column, as other "good" status values are possible, e.g. `"Substituted, Good"` in the Status column. As these are good, they should likely be included. (note expect similar issues in similar functions, e.g re-sampling?)

Typical values we have in the Status column for our data:
![image](https://github.com/rtdip/core/assets/85494120/16c74217-8a0c-4fbb-9234-b4871ccd9c75)

Whilst the query builder only retains values of `"Good"` in the status column: 
https://github.com/rtdip/core/blob/3238de795dc15a2c1ce89b8492730f05c6658abd/src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py#L44

**To Reproduce**

Steps to reproduce the behavior: - N/A do not know what data you have available etc. It would be good for you to have test cases that work on mocked data, reading and outputting that as an end-to-end test.

**Expected behavior**

All good data is used in calculations

**Screenshots**

Included above

**Installation Setup (please complete the following information):**

N/A

**Additional context**

Proposed solution would be something like:

```
AND 'good' in LOWER(`{{ status_column }}`) 
```

**Comment by GBBBAS** [comment]
Hey @matt-hull0 many thanks - we will come back to you on this.

@cching95 - let's look at options to handle this scenario
